env: 'test'
timeout:
  shutdownSeconds: 30
http:
  host: '127.0.0.1'
  port: 0 # PORT 0 randomly assigns a usable port. Set up for parallel testing.
logger:
  level: 'silly' # Log only if less than or equal to this level
  format: 'text'
