name: UI Test

on:
  pull_request:
    branches:
      - main
      - 'develop'
    paths:
      - 'ui/**'
      - '!ui/**/**.md'
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            ui
          fetch-depth: 1
      - name: Read .nvmrc
        working-directory: ./ui
        run: |
          echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm
      - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
      - name: Install dependencies
        working-directory: ./ui
        run: |
          npm ci
      - name: Run UI unit tests
        working-directory: ./ui
        run: |
          npm run test
